### ISSUE TITLE
Support for MeshCatMechanisms.jl

### ISSUE THREAD

**Issue by tkoolen** [JuliaRobotics/RigidBodySim.jl#45]
https://github.com/JuliaRobotics/MeshCatMechanisms.jl

Need to figure out how to implement pause/stop/etc commands sent from the viewer to the simulation environment.

**Comment by rdeits** [comment]
I'm still thinking about how (and whether) I can implement two-way events from the visualizer to the client, but it looks like WebIO.jl is a pretty nice alternative. Creating a control button that lives in an IJulia/jupyterlab cell is pretty easy:

```julia
w = Scope()
obs = Observable(w, "rand-value", 0.0)
on(obs) do x
    println("JS sent $x")
end
w(
  dom"button"(
    "generate random",
    events=Dict("click"=>@js () -> $obs[] = Math.random()),
  ),
)
```

(to get this to work, you'll need to add `WebIO` and `JSEvents` and install the jupyterlab extension per https://github.com/JuliaGizmos/WebIO.jl#getting-started )

Actually, I think it kind of makes more sense to have the controls live in the Jupyter cell (or in a standalone window, which is also possible with WebIO) rather than necessarily living in the meshcat window. Once you have more than one client or more than one simulation trying to add controls to the same meshcat window, things are going to get pretty messy.

**Comment by rdeits** [comment]
Ok, now that MeshCatMechanisms is up to full feature-parity with RigidBodyTreeInspector, I think it's time to pull the trigger on this and drop the whole DrakeVisualizer stack. We can use the WebIO/Observables framework to also totally get rid of the LCM dependency for visualization and play/pause control.

**Comment by tkoolen** [comment]
Sounds great! One decision to make is whether to keep the current visualizer interface abstraction, https://github.com/JuliaRobotics/RigidBodySim.jl/blob/master/src/visualization.jl. Any thoughts?

**Comment by rdeits** [comment]
I think the callbacks and command handler are useful, but we can probably get rid of most of the rest. Here's a rough audit:

* isinteractive(): We're no longer tied to having the buttons live inside the visualizer, so I don't think this function makes sense anymore
* visualize(): MeshCatMechanisms already uses `RBD.set_configuration!` to visualize a given configuration, so we don't need a separate `visualize` function since a hypothetical future vis could just implement set_configuration! for itself
* animate(): This function no longer needs to do any complicated timing because we can now send whole animations with `MCM.setanimation!`. It just needs to pull a vector of times and configurations out of the ODE solution. They don't even need to be downsampled or evenly spaced, since setanimation does its own interpolation. But I think it makes sense for this function to exist since it provides a useful bridge to DiffEq

**Comment by rdeits** [comment]
Oh, and I think we can get rid of `window`. There are a lot of ways you might want to open a vis window, and I think it's better to let the visualizer handle it. If you want a sensible default, MeshCat overloads Base.open for this

**Comment by tkoolen** [comment]
OK, sounds like the current interface is sufficiently misaligned with MeshCat that it would either have to be redesigned or gotten rid of. I don't foresee adding support for a different visualizer anytime soon. Let's not try to predict what would be a good common interface for MeshCat and that hypothetical other visualizer, so let's just nix the interface.

**Comment by rdeits** [comment]
Sounds good. I think it's still worth keeping `animate()` with the current signature (but a different implementation) inside RigidBodySim. But we can just make it a single function instead of setting it up as a generic interface.

**Comment by tkoolen** [comment]
I think we can close this now :slightly_smiling_face:
