### ISSUE TITLE
PeriodicCallback associated with PeriodicController is never created if PeriodicController is called from a different control! function

### ISSUE THREAD

**Issue by rdeits** [JuliaRobotics/RigidBodySim.jl#60]
For example, wrapping a `PeriodicController` in another callable, like: 

```
periodic_controller = PeriodicController(v, dt, inner_controller)
my_controller(T, t, state) = periodic_controller(T, t, state)
dynamics = Dynamics(mech, my_controller)
problem = ODEProblem(dynamics, state)
```

causes the automatic PeriodicCallback not to be added to the ODEProblem, which results in the `inner_controller` only ever being called once, not every `dt`. 

The safest solution seems to be requiring users to add the periodic callback for each periodic controller.

**Comment by rdeits** [comment]
(or at least to have a PeriodicController always error out if its PeriodicCallback was not set up, so we can still automatically detect it when possible)

**Comment by ChrisRackauckas** [comment]
You can just have it always merge and pass in a callback set? I don't know the application so I don't know if that'll produce wonky results.

**Comment by tkoolen** [comment]
(Robin and I talked about this in person)

I currently have things set up so that creating an `ODEProblem` with a `Dynamics` object that has a `PeriodicController` as the `control!` field automatically creates the associated `PeriodicCallback` and uses it to construct the `ODEProblem`. The problem here is that the `control!` function is not itself a `PeriodicController`, but it calls a `PeriodicController`.
